[2025-07-28T12:16:53.132+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: orders_dag.fetch_and_load_orders manual__2025-07-28T12:16:49.900985+00:00 [queued]>
[2025-07-28T12:16:53.151+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: orders_dag.fetch_and_load_orders manual__2025-07-28T12:16:49.900985+00:00 [queued]>
[2025-07-28T12:16:53.152+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-07-28T12:16:53.187+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_and_load_orders> on 2025-07-28 12:16:49.900985+00:00
[2025-07-28T12:16:53.238+0000] {standard_task_runner.py:57} INFO - Started process 4661 to run task
[2025-07-28T12:16:53.281+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'orders_dag', 'fetch_and_load_orders', 'manual__2025-07-28T12:16:49.900985+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/orders_dag.py', '--cfg-path', '/tmp/tmp5h28kh1x']
[2025-07-28T12:16:53.302+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask fetch_and_load_orders
[2025-07-28T12:16:53.483+0000] {task_command.py:416} INFO - Running <TaskInstance: orders_dag.fetch_and_load_orders manual__2025-07-28T12:16:49.900985+00:00 [running]> on host 979e7d3a451f
[2025-07-28T12:16:53.710+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='orders_dag' AIRFLOW_CTX_TASK_ID='fetch_and_load_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-07-28T12:16:49.900985+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-28T12:16:49.900985+00:00'
[2025-07-28T12:16:53.717+0000] {logging_mixin.py:151} INFO - üöÄ Starting data fetch from API...
[2025-07-28T12:16:53.928+0000] {logging_mixin.py:151} INFO - üîé Status Code: 404
[2025-07-28T12:16:53.929+0000] {logging_mixin.py:151} INFO - üîé Raw Response: The deployment could not be found on Vercel.

DEPLOYMENT_NOT_FOUND

sfo1::m6gcn-1753705013895-6e645d339ca5
[2025-07-28T12:16:53.934+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/orders_dag.py", line 31, in fetch_and_load_orders
    raise Exception(f"‚ùå API Request Failed: {response.status_code} - {response.text}")
Exception: ‚ùå API Request Failed: 404 - The deployment could not be found on Vercel.

DEPLOYMENT_NOT_FOUND

sfo1::m6gcn-1753705013895-6e645d339ca5

[2025-07-28T12:16:53.972+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=orders_dag, task_id=fetch_and_load_orders, execution_date=20250728T121649, start_date=20250728T121653, end_date=20250728T121653
[2025-07-28T12:16:54.046+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 11 for task fetch_and_load_orders (‚ùå API Request Failed: 404 - The deployment could not be found on Vercel.

DEPLOYMENT_NOT_FOUND

sfo1::m6gcn-1753705013895-6e645d339ca5
; 4661)
[2025-07-28T12:16:54.104+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-28T12:16:54.175+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
